### ISSUE TITLE
This does not support multiple invocations

### ISSUE THREAD

**Issue by allestaire** [brefphp/local-api-gateway#20]
So unlike kong that it supports multiple lambda funcations, but the problem is, it does not throw the same lambda event as your local api gateway does.

So here is the example:

```
_format_version: "3.0"
_transform: true

routes:
- name: product 
  paths: [ "/product" ]
- name: user
  paths: [ "/user" ]
- name: honojs
  paths: [ "/honojs" ]

plugins:
- route: user
  name: aws-lambda
  config:
    aws_region: eu-west-1
    aws_key: DUMMY_KEY
    aws_secret: DUMMY_SECRET
    function_name: function
    host: user_lambda 
    port: 8080
    disable_https: true
    forward_request_body: true
    forward_request_headers: true
    forward_request_method: true
    forward_request_uri: true
    is_proxy_integration: true
- route: product
  name: aws-lambda
  config:
    aws_region: eu-west-1
    aws_key: DUMMY_KEY
    aws_secret: DUMMY_SECRET
    function_name: function
    host: product_lambda
    port: 8080
    disable_https: true
    forward_request_body: true
    forward_request_headers: true
    forward_request_method: true
    forward_request_uri: true
    is_proxy_integration: true

- route: honojs
  name: aws-lambda
  config:
    aws_region: eu-west-1
    aws_key: DUMMY_KEY
    aws_secret: DUMMY_SECRET
    function_name: function
    host: honojs_lambda
    port: 8080
    disable_https: true
    forward_request_body: true
    forward_request_headers: true
    forward_request_method: true
    forward_request_uri: true
    is_proxy_integration: true
```
